# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help_stock.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: black")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: white\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setEnabled(True)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 70, 721, 471))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("background-color: rgb(46, 52, 54); color: white")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "←"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Как купить?\n"
"\n"
"    1. В поле указываем кол-во рублей, за которые Вы готовы купить BTC\n"
"\n"
"    2. Нажимаем \"Купить\"\n"
"\n"
"    3. Все готово. Вы приобрели BTC\n"
"\n"
"\n"
"Как продать?\n"
"\n"
"    1. Указываем в поле кол-во BTC, которые Вы готовы продать\n"
"\n"
"    2. Нажимаем \"Продать\"\n"
"\n"
"    3. Все готово. Вы продали BTC\n"
"\n"
"\n"
"Обязательные требования для совершения сделок:\n"
"\n"
"    1. Если Вы продаете BTC, то на счету у Вас должно быть данное кол-во BTC\n"
"\n"
"    2. Если Вы покупаете BTC, то на счету у Вас должно быть данное кол-во рублей\n"
"\n"
"    3. Минимальная покупка BTC - от 1000 рублей. Минимальная продажа BTC - 0.0005 BTC\n"
"\n"
"    4. Вы должны ввести корректные данные в настройках (Api & Secret Key)\n"
"\n"
"    5. В настройках API у Вас должно быть разрешение на спотовую и маржинальную торговлю (галочка напротив)\n"
"\n"
"    6. Если все настроено верно, но все равно возникают проблемы - проверьте API - разрешение на торговлю действует 90 дней (далее можно заново разрешить)"))
