# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setEnabled(False)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(245, 35, 261, 131))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(25)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setStyleSheet("background-color: rgb(46, 52, 54); color: white")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_4.setEnabled(False)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(520, 35, 261, 131))
        self.plainTextEdit_4.setStyleSheet("background-color: rgb(46, 52, 54)")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: white")
        self.pushButton.setObjectName("pushButton")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_5.setEnabled(False)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(70, 35, 161, 131))
        self.plainTextEdit_5.setStyleSheet("background-color: rgb(46, 52, 54)")
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(83, 130, 135, 25))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(46, 52, 54); color: white")
        self.label_2.setObjectName("label_2")
        self.wrap = QtWidgets.QPushButton(self.centralwidget)
        self.wrap.setGeometry(QtCore.QRect(680, -10, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.wrap.setFont(font)
        self.wrap.setStyleSheet("color: white; border: none")
        self.wrap.setObjectName("wrap")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(720, 6, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.exit.setFont(font)
        self.exit.setStyleSheet("color: white; border: none")
        self.exit.setObjectName("exit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 530, 300, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "≡"))
        self.label_2.setText(_translate("MainWindow", "Не работает"))
        self.wrap.setText(_translate("MainWindow", "_"))
        self.exit.setText(_translate("MainWindow", "✖"))
        self.label.setText(_translate("MainWindow", "Krytskiy Yan & Ryazanov Daniil"))
